### ISSUE TITLE
Odd startup (and close) behaviour in 1.0.2

### ISSUE THREAD

**Issue by majorproblem** [glimpseio/Splice#12]
When I launch Splice 1.0.2 the "Create and configure…" screen drops down five (!) times before I get a chance to interact with the application. Something that seems to be related is that when I then try to quite the application instead of quitting, the application brings down the "Create and configure…" screen a few time instead and I press "cancel". The number of times the screen appears seems to match the number of times it appears at start, i.e., my feeling is that I have to quit the application an equal number of times (in this case five).

In some cases have this closing behaviour been interrupted by a crash instead.

**Comment by marcprux** [comment]
That is odd. Can you try the following:

1. Launch the app and "cancel" each sheet that opens up
2. For each window that remains open, close it with "File"->"Close Window"
3. Quit Splice
4. Re-launch Splice

Once you re-launch, only a single window should open up with the configuration sheet.

**Comment by majorproblem** [comment]
Thanks, that solved it!
