### ISSUE TITLE
SSL Error when connecting to Heroku PostgreSQL server

### ISSUE THREAD

**Issue by CodeMeister** [glimpseio/Splice#13]
When trying to connect over SSL I get the error:

SSL error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I have no problem connecting over SSL to this database from other software apps.

Is there a setting I'm missing?

**Comment by marcprux** [comment]
Can you let us know the type of database you are connecting to, and whether it is hosted locally or on a cloud server?

**Comment by CodeMeister** [comment]
Hi, I'm testing with one of the free Heroku Postgres (10.0) databases.

**Comment by marcprux** [comment]
We don't include the Heroku certificate in Splice currently. For the time being, you should be able to work around the issue by clicking the "Advanced" tab for the connection configuration, and in the row with the key "sslfactory" setting the value to be: "org.postgresql.ssl.NonValidatingFactory".

Please let us know if this works for you.

**Comment by CodeMeister** [comment]
That worked for me.   Many thanks
