### ISSUE TITLE
Password Required

### ISSUE THREAD

**Issue by CodeMeister** [glimpseio/Splice#14]
Is there a way to turn the password requirement off, so I can access a local db that has no password?

**Comment by marcprux** [comment]
That's a good point. There currently isn't a way to leave them blank for the pre-defined database types, so to use a blank password, you would need to configure using the "JDBC Driver", which requires that you manually configure the JDBC driver issue.

We will make the password field non-required in the version that is released after 1.0.3 (which is already being processed for release).
