### ISSUE TITLE
Problem after upgrade

### ISSUE THREAD

**Issue by CastelloD** [glimpseio/Splice#20]
Hi all, 
after today's update of Splice , I have this error:

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/libssh2/lib/libssh2.1.dylib
  Referenced from: /Applications/Splice.app/Contents/Frameworks/Glean.framework/Versions/A/Glean
  Reason: image not found
```

```
My OS version is:
OS Version:            Mac OS X 10.14.1 (18B75)
```

Any suggestions?

Thanks,
Daniele

**Comment by marcprux** [comment]
We're working on a fix for this. We hope to have it released sometime today or tomorrow.

**Comment by CastelloD** [comment]
> We're working on a fix for this. We hope to have it released sometime today or tomorrow.

Thanks for the reply.

Daniele

**Comment by olewery** [comment]
Looks like you linked against a home-brew version of libssh2. `brew install libssh2` fixes this for me on Mohave and High Sierra. 

I'm surprised that got through the App Store process these days.

**Comment by marcprux** [comment]
You’re exactly right @blatherus, and you’re workaround should work until 1.2.1 is approved. 

We’re surprised as well that it got through.

**Comment by marcprux** [comment]
We're happy to report that Splice 1.2.1 has been released, which resolves the issue.
