### ISSUE TITLE
FR: Ablity to use filter without waiting for SELECT * to complete

### ISSUE THREAD

**Issue by jcohlmeyer** [glimpseio/Splice#8]
When I first open a table I have to wait for the SELECT * to complete before I can use the filter tab to filter results, this can take a long time on a table with many rows.

It would be great if there was a feature where we could use the filter options without having to wait for the return of SELECT *

**Comment by marcprux** [comment]
You can avoid having to perform an initial query by expanding the columns underneath the table tree and selecting all of the columns you would like to include in the filter. The column selection drop-down in the filter expression builder will contain all of the highlighted columns.

**Comment by jcohlmeyer** [comment]
I find this to be a very non-intuitive and sub par answer. I would like to see at least a preference where the auto initial query does not happen if the row count is over X, using a simple row count query before doing the initial lookup.
